#include "setup_types.h"

#ifndef SETUP_DEFAULT_CONFIG_H
#define SETUP_DEFAULT_CONFIG_H

#define DEFAULT_INFERENCE_MODEL_NAME MODEL_PHI_NAME
#define DEFAULT_INFERENCE_MODEL_URL MODEL_PHI_URL
#define DEFAULT_INFERENCE_CPU_CORES 8.00
#define DEFAULT_INFERENCE_THREAD_COUNTS 8.00

#define DEFAULT_EMBEDDING_CPU_CORES 4.00
#define DEFAULT_EMBEDDING_THREAD_COUNTS 4.00

#define DEFAULT_ALLOW_ORIGIN_NAME "*"

#define DEFAULT_HTTPS_ENABLED 0
#define DEFAULT_HTTPS_CERT_PATH_HOST "*"
#define DEFAULT_HTTPS_CERT_PATH_CONTAINER "*"
#define DEFAULT_HTTPS_CERT_NAME "cert.pem"
#define DEFAULT_HTTPS_PRIVKEY_NAME "privkey.pem"
#define DEFAULT_HTTPS_CA_NAME "chain.pem"
#define DEFAULT_APP_EXPOSE_PORT "8000"

#define DEFAULT_PLUGIN_ENABLED 0

#define DEFAULT_SYSTEM_INSTRUCTION "*"

#define DEFAULT_STATIC_API_KEY_ENABLED 0
#define DEFAULT_STATIC_API_KEY "*"

#define DEFAULT_DEFAULT_DATASET_ENABLED 0
#define DEFAULT_DEFAULT_DATASET_NAME "production_dataset"

#define DEFAULT_API_INDEX_DOC_ENABLED 1
#define DEFAULT_API_INDEX_STATS_ENABLED 1
#define DEFAULT_API_INDEX_HEALTHY_ENABLED 1
#define DEFAULT_API_INDEX_CHATBOX_ENABLED 1
#define DEFAULT_API_INFERENCE_COMP_ENABLED 1
#define DEFAULT_API_INFERENCE_RAG_ENABLED 1
#define DEFAULT_API_TOKEN_ENABLED 1
#define DEFAULT_API_EMBEDDING_CALC_ENABLED 1
#define DEFAULT_API_EMBEDDING_DS_ENABLED 1
#define DEFAULT_API_VERSION_ENABLED 1

#define DEFAULT_DEV_MODE_ENABLED 0

#define DEFAULT_DATABASE_BIND_PATH "./lancedb"

#endif